-- Equivalente a 01_schema.sql y 02_seed.sql para instalaciones nuevas.
-- En la base existente, donde ya se ejecutaron manualmente, NO ejecutar esta migración.

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES roles(id),
    username VARCHAR(80) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT users_email_not_blank CHECK (length(btrim(email)) > 0)
);

CREATE UNIQUE INDEX users_email_unique_ci ON users (lower(email));

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT categories_parent_not_self CHECK (parent_id IS DISTINCT FROM id),
    CONSTRAINT categories_name_not_blank CHECK (length(btrim(name)) > 0)
);

CREATE INDEX categories_parent_id_idx ON categories (parent_id);
CREATE UNIQUE INDEX categories_root_name_unique ON categories (lower(name)) WHERE parent_id IS NULL;
CREATE UNIQUE INDEX categories_child_name_unique ON categories (parent_id, lower(name)) WHERE parent_id IS NOT NULL;

CREATE TABLE brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT brands_name_not_blank CHECK (length(btrim(name)) > 0)
);

CREATE UNIQUE INDEX brands_name_unique_ci ON brands (lower(name));

CREATE TABLE sizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE colors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL UNIQUE,
    hex_code CHAR(7),
    CONSTRAINT colors_hex_format CHECK (hex_code IS NULL OR hex_code ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    brand_id BIGINT REFERENCES brands(id) ON DELETE RESTRICT,
    name VARCHAR(180) NOT NULL,
    description TEXT,
    base_price NUMERIC(12, 2) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT products_name_not_blank CHECK (length(btrim(name)) > 0),
    CONSTRAINT products_price_nonnegative CHECK (base_price >= 0)
);

CREATE INDEX products_category_id_idx ON products (category_id);
CREATE INDEX products_brand_id_idx ON products (brand_id);

CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    size_id BIGINT NOT NULL REFERENCES sizes(id) ON DELETE RESTRICT,
    color_id BIGINT NOT NULL REFERENCES colors(id) ON DELETE RESTRICT,
    sku VARCHAR(80) NOT NULL UNIQUE,
    stock INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT variants_product_size_color_unique UNIQUE (product_id, size_id, color_id),
    CONSTRAINT variants_sku_not_blank CHECK (length(btrim(sku)) > 0),
    CONSTRAINT variants_stock_nonnegative CHECK (stock >= 0)
);

CREATE INDEX variants_product_id_idx ON product_variants (product_id);

CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    alt_text VARCHAR(255),
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT images_url_not_blank CHECK (length(btrim(image_url)) > 0)
);

CREATE INDEX images_product_id_idx ON product_images (product_id);
CREATE UNIQUE INDEX images_one_primary_per_product ON product_images (product_id) WHERE is_primary;

CREATE TABLE favorites (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, product_id)
);

CREATE INDEX favorites_product_id_idx ON favorites (product_id);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    total_amount NUMERIC(12, 2) NOT NULL,
    recipient_name VARCHAR(160) NOT NULL,
    shipping_address TEXT NOT NULL,
    shipping_city VARCHAR(120) NOT NULL,
    shipping_postal_code VARCHAR(30) NOT NULL,
    shipping_country VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT orders_status_valid CHECK (status IN ('PENDING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT orders_total_nonnegative CHECK (total_amount >= 0),
    CONSTRAINT orders_recipient_not_blank CHECK (length(btrim(recipient_name)) > 0),
    CONSTRAINT orders_address_not_blank CHECK (length(btrim(shipping_address)) > 0)
);

CREATE INDEX orders_user_created_idx ON orders (user_id, created_at DESC);
CREATE INDEX orders_status_idx ON orders (status);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
    variant_id BIGINT NOT NULL REFERENCES product_variants(id) ON DELETE RESTRICT,
    product_name VARCHAR(180) NOT NULL,
    sku VARCHAR(80) NOT NULL,
    size_name VARCHAR(30) NOT NULL,
    color_name VARCHAR(60) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    CONSTRAINT order_items_variant_unique UNIQUE (order_id, variant_id),
    CONSTRAINT order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT order_items_price_nonnegative CHECK (unit_price >= 0)
);

CREATE INDEX order_items_order_id_idx ON order_items (order_id);
CREATE INDEX order_items_variant_id_idx ON order_items (variant_id);

CREATE TABLE banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    description TEXT,
    image_url TEXT NOT NULL,
    link_url TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT banners_title_not_blank CHECK (length(btrim(title)) > 0),
    CONSTRAINT banners_image_not_blank CHECK (length(btrim(image_url)) > 0),
    CONSTRAINT banners_dates_valid CHECK (starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at)
);

INSERT INTO roles (id, name) VALUES
    (1, 'ROLE_ADMIN'),
    (2, 'ROLE_USER');

SELECT setval(pg_get_serial_sequence('roles', 'id'), (SELECT MAX(id) FROM roles));

INSERT INTO categories (name, description) VALUES
    ('Mujer', 'Ropa y accesorios para mujer'),
    ('Hombre', 'Ropa y accesorios para hombre'),
    ('Unisex', 'Prendas y accesorios unisex');

INSERT INTO sizes (name, sort_order) VALUES
    ('Única', 0), ('XS', 1), ('S', 2), ('M', 3), ('L', 4), ('XL', 5), ('XXL', 6);

INSERT INTO colors (name, hex_code) VALUES
    ('Sin color', NULL), ('Negro', '#000000'), ('Blanco', '#FFFFFF'),
    ('Azul', '#2563EB'), ('Rojo', '#DC2626'), ('Beige', '#D6C6A6');
